disabled_rules:
- cyclomatic_complexity
- trailing_whitespace
- variable_name
- opening_brace
- line_length
- function_body_length
- type_body_length
# - valid_docs
# - type_name
# opt_in_rules:
# - empty_count
# - missing_docs
# - force_unwrapping
